apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kokot-gitops
  description: This is GitOps manifest for kokot   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: kokot
    backstage.io/kubernetes-id: kokot 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: jrichter-rhtap/node1311-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:kokot
